### ISSUE TITLE
month names not capitalized

### ISSUE THREAD

**Issue by rntz** [talonvoice/lexicon#14]
Re https://github.com/knausj85/knausj_talon/issues/760: we still need to use words_to_replace to replace month names, because some of them aren't capitalized. January & February are, but no other month names are.

Not capitalized that should be (IMO): `April June July August September October November December`. (And their derivatives, eg. `April's`.)

Of these, August is arguable since it's also an adjective (https://en.wiktionary.org/wiki/august). But the month is much more common. I haven't included 'may' or 'march' because they're very common English words.

**Comment by lunixbochs** [comment]
thanks!
